name: ci

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4.1.4
      - uses: DeterminateSystems/nix-installer-action@v10
      - uses: cachix/cachix-action@v14
        with:
          name: abiopetaja
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Build thesis document
        run: nix build
      - name: Release
        uses: softprops/action-gh-release@v2.0.2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: result/*.pdf
          generate_release_notes: true

